# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: 'web-ci'

trigger:
  branches:
    include:
      - main
  paths:
    include:
    - web/*
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: ACRCredential@0
  inputs:
    azureSubscriptionEndpoint: 'Visual Studio Enterprise Subscription(03baf857-7c17-4952-9100-7cb6b7b4d8a9)'
    resourceGroupName: 'subsc_manager_rg'
    containerRegistry: 'subscmanageracr'
    actionType: 'show'

- script: |
    cd web
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'
